---
title: "Assignment"
output: html_document
editor_options: 
  chunk_output_type: console
---
Autor: Ferdinand Bubeck,
Ort: DHBW Karlsruhe,
Kurs: WWI19B4,
Vorlesung: Social Network Analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Mögliche Fragestellungen
- Welche Produkte werden nur in Verbindung mit anderen Produkten gekauft?
- Welche Produkte sind zentral?


### Laden der Libraries
```{r libraries, message=FALSE, warning=FALSE}
library("tidyverse")
library("tidygraph")
library("igraph")
library("ggraph")
```

### Laden der Daten
```{r data}
amazon <- read.table("Data/Amazon0302.txt")
```

### Data Exploration
```{r exploration}
head(amazon)

# Count NAs
which(is.na(amazon))
```

### Data Manipulation
```{r manipulation}
dat <- amazon %>% 
  rename(
    from = V1,
    to = V2
  ) %>% 
  mutate(
    from = from+1,
    to = to+1
  )

```

### Fitting Graph Object
```{r net}
net <- as_tbl_graph(dat)


degree <- degree(net)

# Adjacency Matrix
adjacencyMatrix <- net[]

```

### Data Visualization
```{r viz, message=FALSE, warning=FALSE}
degree_df <- as.data.frame(degree)


ggplot(data = degree_df, aes(x=degree))+
  geom_bar(fill = "blue", colour = "blue", alpha=.5)+
  scale_y_continuous(trans='log2')+
  xlim(0,150)+
  labs(title = "Histogram of Node-Degrees", subtitle = "Amazon Network Analyis", y = "Frequency (log2 scale)", x = "Degree of Vertices (xlim = 150)")+
  theme_classic()



```

### Experimental Data
```{r message=FALSE, warning=FALSE}
dat_exp <- dat[1:200,]

net_exp <- as_tbl_graph(dat_exp)

net_exp <- net_exp %>% 
  activate(nodes) %>% 
  mutate(
    degree = centrality_degree()
  )

# network diagramm
ggraph(net_exp, layout = 'kk', maxiter = 100) + 
  geom_node_point(aes(size=degree)) + 
  geom_edge_link(alpha = 0.25) +
  theme_graph()

# coord diagramm
ggraph(net_exp, layout = 'linear', circular = TRUE) + 
  geom_node_point() +
  geom_edge_arc() +
  theme_graph()
```




